### ISSUE TITLE
Jump to next month and back

### ISSUE THREAD

**Issue by slodub** [eouia/MMM-CalendarExt2#2]
I read thru configuration and I didn't see much on the ability to view the entire upcoming month in month view. Is this possible with this version? If not, what options are there for viewing events over a month out? Thanks and merry xmas!!

**Comment by thebmfinn** [comment]
I am heading down this path, looks like the fromNow field in view could be updated. I believe this is accomplished by an external notification (eg. from a button press).  

https://github.com/eouia/MMM-CalendarExt2/wiki/2c.-Configuration:View

**Comment by eouia** [comment]
@slodub @thebmfinn 
You need to prepare 2 views and 2 scenes. I'll call those are "VIEW_THIS_MONTH", "VIEW_NEXT_MONTH" and "SCENE1", "SCENE2".
Set `fromNow` of VIEW_THIS_MONTH to `0` and set `fromNow` of VIEW_NEXT_MONTH to `1`
SCENE1 would have VIEW_THIS_MONTH. 
SCENE2 would have VIEW_NEXT_MONTH.
Now, you can rotate scenes with `rotateInterval` or notifications.

**Comment by thebmfinn** [comment]
Thanks @eouia 

So in your example, there would be n number of scenes and views for however many months you'd like to be able to look ahead. rotateInterval looks like it would automatically update to scroll through these.

Are there any good examples on how MMM-CalendarExt2 listens and updates values (eg fromNow) from notifications?

**Comment by eouia** [comment]
Dynamic changing on runtime is not supported. Because, I think nobody would not really want to see 1 year later schedules on his mirror. I always regard MM as a glancing-gadget not main-working-platform. We have better gadgets for that purpose like a smartphone.
The main reason is, lack of input methods. Maybe some people are using voice-commander, gesture-sensors, but most users don't have anything. Without proper rich input method, that feature is just a feature which be not used. Furthermore, your input-related-module should emit proper notification to order so complex request. But notifications of most modules cannot be customized as our needs.

Funny thing is, My ex MMM-CalenderExt has a feature of dynamic configuration on runtime. But as I know, nobody has asked me about that feature. :D No one seems to use that feature. Thus, I remove that feature on this module MMM-CalendarExt2.

Still I believe if you want one or two month later schedules, just make scene-view for it. It would be easier. 

Anyway, I'll consider to add that feature. I think it's not difficult to program it, but real usage might be somehow difficult. Notification should have indications about target scene-view and some configuration values.

**Comment by eouia** [comment]
You can use dynamic runtime view with MMM-CalendarExt https://github.com/eouia/MMM-CalendarExt/wiki/Use-Notification-(for-module-developers)#calext_modify_config
It has similar features (and more) with this module. Looks are somewhat different but you can adjust with CSS. (but timeline style view of `month` and `week` is not supported)

**Comment by thebmfinn** [comment]
@eouia I really appreciate your quick responses! Thanks for all of the information, I'll play with MMM-CalendarExt a bit.

**Comment by eouia** [comment]
I'll close this issue, have a nice day.
