### ISSUE TITLE
Upcoming Events View - event details overflowing 

### ISSUE THREAD

**Issue by thebmfinn** [eouia/MMM-CalendarExt2#3]
See the linked image below, I was hoping for some pointers on how to control the overall height of the event slot in the Upcoming View. It seems that the calendar event created by google has some extra properties/text and the context are pretty large.

http://i.imgur.com/boRnD69.png

Also, could you quickly comment on how to allow for multiple lines (text wrapping) for the Month View events. I would like like to allow for longer event titles (more description, multiple lines).

**Comment by eouia** [comment]
If you don't want to see the description of ALL events in agenda style views(upcoming, current),
add this to your `css/custom.css`
```
/* Only for agenda slot */
.CX2 .agenda .eventSub {
  display:none;
}
```

If you remove description of specific calendar (e.g: calendar ClassName : `Holiday`) in agenda views,
add this to your `css/custom.css`
```
.CX2 .agenda .Holiday .eventSub {
  display:none;
}
```

**Comment by eouia** [comment]
And with CSS, you can allow multi-line of event Title of month, week view. But I don't recommend, because there is not enough margin to keep  multi-lines.

**Comment by eouia** [comment]
Have you still this problem got? There is no feedback so I will close this issue. You can continue this issue or another anytime. Have a nice day.

**Comment by thebmfinn** [comment]
I have been trying to use CSS to create 2 line (or more depending on font size) slots, I find that the one line just isnt long enough for meaningful titles. I have tried variations of the following without the desired result:

```
.CX2 .weekSlot .eventTitle{
overflow: visible;
white-space: normal;
}
```

**Comment by AndrewSav** [comment]
@eouia can you help here please? as @thebmfinn says one line just isnt long enough for meaningful titles - nothing fits. How can this be solved? Can you give some css examples?

**Comment by eouia** [comment]
No, 
These week/month view is not made for that kind of purpose. Those views are somewhat summary or overview.  For the details, use together with other views like `current` or `upcoming` or `daily`,...
If title has multi-lines, it means it will occupy more space, so other events couldn't be displayed. That's definitely not so good.
Every calendar program like `Google calendar` or `Calendar` on Mac, Office365... has only abbreviated 1 line title in a month/week style view also for the same reason.

Available alternative approach;
- make shorter title or give meaning with `transform` to the event:
For example; 
Your event would have titled "Birthday of Jessica". It might be a bit long for week/month cell.
```js
transform: (event)=>{
  if (event.title.search("Birthday of") > -1) {
    event.icon = "fxemoji-birthdaycake" // This will give an icon for this kind of event.
    event.title = event.title.replace("Birthday of", "") // This will delete `Birthday` title.
    event.className = "somecss_class" // This will give some CSS class to this event.
  }
  return event
}
```

- Or try other view(or plugin) like `MMM-CalendarExtPlan`. It is an alternative plugin view , it could show multi-line title.
![](https://raw.githubusercontent.com/eouia/MMM-CalendarExtPlan/master/screenshot.png)
https://github.com/eouia/MMM-CalendarExtPlan#styling

**Comment by AndrewSav** [comment]
Thank you for this. I mostly asked, because I'm not very good with css in particular, so it was not obvious for me how to try and see what it looks like with two lines per slot. I suspect that you are right, and that there is no way to make it look good if these take up two lines but I wanted to have a look myself to form that conclusion, I just did not know how to tweak css in order to see that.

Another idea would be is try to reduce the font size for them: simiallarily I do not know how to do it with css, because I'm proficient with that enough.

I was hoping if you could provide those examples so I could play with them and see if I could arrive to something satisfactory.

The goal is to be able to display 4 weeks schedule on one screen that is actually useful.

I cannot see any multuiline titles on the screenshot above, also it's not the 4 weeks view I'm after.

Thank you for all your help. If you could give the css examples I mention above that would be great.

**Comment by eouia** [comment]
Dimension of width/heigh of event in the week/month view is hardcoded with calculation, so not so easily patched with only CSS. It needs source modification.
