### ISSUE TITLE
help needed in event positioning

### ISSUE THREAD

**Issue by GattoJohnny** [eouia/MMM-CalendarExt2#30]
Hi @eouia ,

Can you, please, help me out with positioning the events in week view? Now they overlap the header area and are slightly wider than the container cell.
![CalExt2-positioning_event2](https://user-images.githubusercontent.com/47010649/63759910-9de6c980-c8be-11e9-944a-4222b6ba4514.jpg)

Custom.css goes like this:

> .CX2 .cellSlot .slotSubTitle {
>   color:#3A6061;
> }
> 
> .CX2 .cellSlot .slotTitle {
>   color:#999;
>   text-alignment: "right";
> }
> 
> .CX2 .cellSlot.weekday_6 .slotSubTitle {
>   color:#3A6061;
> }
> 
> .CX2 .cellSlot.weekday_6 .slotTitle {
>   color:#999;
> }
> 
> .CX2 .cellSlot.weekday_7 .slotSubTitle {
>   color:#661414;
> }
> 
> .CX2 .slot{
>   padding:0px 4px;
>   border:4px solid #000000;
> }
> 
> .CX2 .slot .slotHeader {
>   background-color:#000000;
>   border-top:2px solid #3A6061;
>   border-bottom:2px solid #3A6061;
>   margin-top:5px;
>   margin-bottom:15px;
>   height:calc(var(--font-size) + 6px);
>   font-weight:normal;
>   padding:6px 6px 0;
> }
> 
> .CX2 .today .slotHeader { /* today slot */
>   background-color:#afcecf;
> /*  background-color:#080a0a;*/
>   color:#999;
> }
> 
> .CX2 .today .slotHeader * {
>   color:#999;
> }
> 
> .CX2 .today .slotSubTitle {
>   color:#3A6061;
> }
> 
> .CX2 .weekSlot {
>   position:relative;
> }
> 
> .CX2 .today.slot {
>   background-color:#afcecf;
> /*  background-color:#080a0a;*/
>   border:4px solid #1d2f30;
> }
> 
> .CX2 .slot > .slotContent{
>   position:relative;
>   width:100%;
>   background-image: none;
> }
> 
> .CX2 .module-content { /* fake module body */
>   color:#999;
>   font-family: 'Roboto', sans-serif;
> }
> 
> .CX2 .weeksmark {
>   display:none;
> }
> 
> 
> /***** Event *****/
> 
> .CX2 .event {
>   padding:5px;
>   margin:2px 0;
>   background-color:rgba(64,64,64,0.6);
>   position:relative;
>   text-align:left;
> }
> 
> .CX2 .event.fullday {
>   border-radius:5px;
>   background-color:#FFF;
>   color:#000;
> }

Thanks in advance.

**Comment by eouia** [comment]
Hmmm.. it's due to `margin`. `getBoundingClientRect()` doesn't include `margin` so, my module miscalculated your `slot` and `slotHeader`'s height (Exactly says, calculation of height was right, but couldn't consider the margin)
The problem is, calculation of margin is not so easy. I think I can rewrite that routine on next updates, but at this moment, it couldn't.

Or you can rewrite your CSS to use padding of children instead margin of parents. It might be some code-juggling. So sorry.

**Comment by GattoJohnny** [comment]
Thank you for the quick reply. Looking forward to the update.

By the way, how can I wrap long lines, like "oneLineEvent:0" did in CalExt?

**Comment by eouia** [comment]
It would be wrapped automatically. wouldn't? Or you don't want to wrap? (I don't recommend in week/month view)

**Comment by GattoJohnny** [comment]
Q1) I finally figured that the alignment issue can be cured by adding some margins to _.event_ and _.event.fullday_:

> .CX2 .event {
>   padding:5px;
>   **margin:12px 0 0 8px;**
>   background-color:transparent;
>   position:relative;
>   text-align:left;
> }
> 
> 
> .CX2 .event.fullday {
>   border-radius:unset;
>   background-color:transparent;
>   color:#999;
>   **margin:12px 0 0 8px;**
> }

Plus amended the style a bit. Now it looks like this.
![CalExt2-Margins+Wrap](https://user-images.githubusercontent.com/47010649/63771579-badbc680-c8d7-11e9-926e-ec0a727a4c4f.jpg)

Q2) Regarding the line wrap, by default it DOES NOT wrap in my config. As you can see above long lines are truncated.

**Comment by eouia** [comment]
Sorry for my confusing. I meant truncating(ellipsis ...). 

In week/month views, wrapping(different heights among events) cause another position problem. Because multi-day events should across a few cells with pre-calculated Y coordination. But if some event would have different height on run-time, The calculation will be failed totally. Unfortunately, dynamical fluidic CSS is very difficult. (If you are THE ONE, please make a PR for me. :D)

Here is my suggestion;
1) Use dedicated icon & style by filtering title (e.g: "John's Birthday" => cake icon with "John")
2) You can change long title shortly or abbreviation by transform feature. (e.g: "Los Angeles" => "LA")
3) Use additional views like `daily` or `upcoming` together to get detail information of events.  


Sorry again. However You win some, you lose some.

**Comment by klaernie** [comment]
@GattoJohnny try the [text-overflow](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp) property on the label.

**Comment by GattoJohnny** [comment]
@eouia, thanks for the hints. And don't worry about the fluidic CSS, this module is awesome and I'm grateful for such a prompt and excellent support from you.

@klaernie, I think it already works by the ellipsis rendering method. All the other options look worse. Anyway, thank you for the inspiration of my Calendar formatting. I liked your sample calendar with the colored vertical bars.
