### ISSUE TITLE
Order of fake modules

### ISSUE THREAD

**Issue by AndrewSav** [eouia/MMM-CalendarExt2#58]
MagicMirror promises that modules in the same position are loaded in the order specified in the config.

I want to use MMM-CalendarExt2 in the bottom_bar and I also want to use [WB-Weather](https://github.com/delightedCrow/WallberryTheme/blob/master/WB-weather/README.md) in bottom bar.

I want MMM-CalendarExt2 to appear before WB-Weather.

To this end, I specify the MMM-CalendarExt2 module _before_ WB-Weather in the config.

But because MMM-CalendarExt2 create fake module for views, it's inserts the view _at the bottom_ of WB-Weather.

MMM-CalendarExt2 should not do that. In should honour the order of config file, as per MagicMirror promise.

![mmm](https://user-images.githubusercontent.com/658865/74510176-11ad8900-4f68-11ea-8234-4245dd0a0a12.png)

[This line](https://github.com/eouia/MMM-CalendarExt2/blob/4618e429b4e5885d8641c448f75ab98ed332f4bf/CALEXT2_View.js#L115) inserts it at the bottom of everything else.

**Comment by eouia** [comment]
Hmmm. My previous MMM-CalendarExt has `positionOrder` to control that issue, but It looks nobody cares about it. So I didn't implement that feature in this module.
fake_module is inevitable to keep multi-views in one module. I think legacy position system of MM is not so good but anyway we should respect it.
I'll add `positionOrder` for view as soon as possible.
Sorry for the inconvenience.

**Comment by AndrewSav** [comment]
Thanks a lot!

**Comment by eouia** [comment]
Yes, I like this simplicity, but current legacy way of handling display of module is somewhat restricted. only one position in fixed region for one module could give a limitation of displaying. If I were, I might have considered `accumulated transparent windows` instead of `flat table style division`.  Or at least, using `flex` or `grid` model of CSS. Anyway, I respect the current. :)

`positionOrder` is added.

**positionOrder:-1** (default)
![image](https://user-images.githubusercontent.com/1720610/74513506-05471300-4f0b-11ea-8087-42d86b635576.png)



**positionOrder:0**
![image](https://user-images.githubusercontent.com/1720610/74513561-227be180-4f0b-11ea-83cf-08ad2e68fe42.png)


**positionOrder:1**
![image](https://user-images.githubusercontent.com/1720610/74513602-3fb0b000-4f0b-11ea-8332-0dbf5f2008db.png)

**Comment by AndrewSav** [comment]
Working fine!
